### ISSUE TITLE
Backup / Restore

### ISSUE THREAD

**Issue by rdggithub** [morris/vanilla-todo#11]
I'm using some simple Bookmarklets to backup/restore the local storage of this app to/from JSON... would be great to see this implemented via the UI.

PS: I'm actually using this for my private stuff, pretty cool, thank you for creating it!

**Comment by morris** [comment]
Hi, thanks for the idea! Can you point me to resources on how something like this could be implemented? And another question: Wouldn't this be covered by setting up browser syncing as provided by most popular browsers? Cheers!

**Comment by rdggithub** [comment]
I'm using those from
https://github.com/todvora/localstorage-backup

Browser syncing would mean I'm giving away the data, and it's not encrypted or zero knowledge or stuff, from what I guess? Therefore I prefer to locally backup it.

It's not an important enhancement, I guess, but you put that much effort into the script, I'd love if it would be useful to some people and for me the backup function was crucial when deciding to work with it.

Again, thank you very much for sharing!

**Comment by morris** [comment]
Finally got around to it :) thanks for the idea & enjoy!

**Comment by rdggithub** [comment]
Very cool, thank you!
