### ISSUE TITLE
Task created twice when clicking on section headline

### ISSUE THREAD

**Issue by n0nick** [morris/vanilla-todo#4]
Steps to reproduce:
1. Click "Add" button on the righthand
2. Focus on task item and type something "foo"
3. While focus is still on task name input, click on section headline ("...")

Expected:
Task "foo" created and focus shifts to section headline

Actual:
Task "foo" created twice

Screencast: 
![Kapture 2020-10-27 at 11 14 15](https://user-images.githubusercontent.com/206795/97321984-bd241280-1845-11eb-9951-3a2401a59218.gif)

**Comment by morris** [comment]
Thanks a lot, that's terrible, I will take a look!

**Comment by morris** [comment]
Think I got it, thanks and let me know if you find anything else. I will add a contributions section (or file) soon and list you there if that's alright :)

**Comment by n0nick** [comment]
You're quick :) Confirming this is fixed now.
Thanks! I really like the concept of this project and how you've implemented this.
